/*
-- Omitidos

EMBALAJE
SNDECLARACION
NIT_EXPORTADOR
NOMBRE_EXPORTADOR
SUBPARTIDA
DESCRIP_SUBPARTIDA
UNIDAD_SUBPARTIDA
BULTOS
UNIDAD_COMERCIAL
NMCONVERSION
[B] COD_ZONAFRANCA
[B] COD_PAIS_PROCEDENCIA
[B] PAIS_PROCEDENCIA
[B] FMM
[B] CDFACTURA 
[B] CDDOC_TRANSPORTE
[B] CDDOC_EXPORTACION

-- Medidas

TASA_CAMBIO
CANTIDAD
PRECIO
PESO_BRUTO
PESO_NETO
FLETES
FOB

*/

-------Paises
/*
-- Paises
Pais Cod_pais

COD_PAIS_ORIGEN
PAIS_ORIGEN
COD_PAIS_COMPRA
PAIS_COMPRA
COD_PAIS_DESTINO
PAIS_DESTINO
COD_PAIS_BANDERA
BANDERA
*/

DROP TABLE IF EXISTS DimCountry;

SELECT
    COD_PAIS_ORIGEN AS CountryId,
    PAIS_ORIGEN as CountryName
INTO DimCountry
FROM DataSemilla
GROUP BY COD_PAIS_ORIGEN, PAIS_ORIGEN;

UPDATE DimCountry
SET CountryId = 0, 
    CountryName = 'N/A'
WHERE CountryId IS NULL AND CountryName IS NULL

ALTER TABLE DimCountry
ALTER COLUMN CountryId int NOT NULL;

SELECT *
FROM DimCountry
ORDER BY CountryId;


--------TIEMPO

/*

-- Tiempo
Año Mes Dia Hora Cuarto Semestre 
FECHA_DEFINITIVO
FECHA_APROBACION
FECHA_EJECUCION
FECHA_REVISION
FECHA_RECHAZO
FECHA_DIGITALIZACION
*/
DROP TABLE IF EXISTS DimDate;

WITH
    combinedDates
    AS

    (

            SELECT DISTINCT FECHA_APROBACION
            FROM DataSemilla
        UNION
            (
            SELECT FECHA_DEFINITIVO
            FROM DataSemilla
    )
        UNION
            (
            SELECT FECHA_DIGITALIZACION
            FROM DataSemilla
    )
        UNION
            (
            SELECT FECHA_EJECUCION
            FROM DataSemilla
    )
        UNION
            (
            SELECT FECHA_RECHAZO
            FROM DataSemilla
    )
        UNION
            (
            SELECT FECHA_REVISION
            FROM DataSemilla
    )
    )
SELECT DISTINCT
    YEAR(FECHA_APROBACION) AS DateYear,
    MONTH(FECHA_APROBACION) AS DateMonth,
    DAY(FECHA_APROBACION) AS DateDay,
    DATEPART(hour,FECHA_APROBACION) AS DateHour
INTO DimDate
FROM combinedDates
ORDER BY 
        DateYear, 
        DateMonth, 
        DateDay, 
        DateHour;

ALTER TABLE DimDate 
ADD DateId INT IDENTITY(1,1) PRIMARY KEY;

SELECT *
FROM DimDate
ORDER BY DateYear, 
        DateMonth, 
        DateDay, 
        DateHour;


---------------------------------------PRODUCTO
/*
COD_ITEM
ITEM
TIPO_ITEM
UNIDAD_MEDIDA
EMBALAJE
*/
DROP TABLE IF EXISTS DimProduct;

SELECT DISTINCT 
    COD_ITEM, 
    ITEM,
    TIPO_ITEM,
    UNIDAD_MEDIDA
INTO DimProduct
FROM Datasemilla;

ALTER TABLE DimProduct 
ADD ProductId INT IDENTITY(1,1) PRIMARY KEY;

SELECT * FROM DimProduct;

-- SELECT  ITEM, TIPO_ITEM, UNIDAD_MEDIDA, COUNT(COD_ITEM) as count
-- FROM DimProduct
-- GROUP BY  ITEM, TIPO_ITEM, UNIDAD_MEDIDA
-- HAVING COUNT(COD_ITEM) > 1;


---------------------------------------SIA

/*

NIT_SIA
NOMBRE_SIA

*/

DROP TABLE IF EXISTS DimSia;

SELECT DISTINCT 
    NIT_SIA, 
    NOMBRE_SIA
INTO DimSia
FROM Datasemilla;

ALTER TABLE DimSia
ADD siaID INT PRIMARY KEY IDENTITY(1,1);


SELECT *
FROM DimSia;



--------------------------------------- TRANSACTION

/*
TIPO
CDTRANSACCION
DSTRANSACCION
*/

DROP TABLE IF EXISTS DimTransaction;

SELECT DISTINCT 
    CDTRANSACCION, 
    DSTRANSACCION
INTO DimTransaction
FROM Datasemilla;

ALTER TABLE DimTransaction
ALTER COLUMN CDTRANSACCION INT NOT NULL;

ALTER TABLE DimTransaction
ADD CONSTRAINT DimTransaction_PK PRIMARY KEY (CDTRANSACCION);

SELECT *
FROM DimTransaction;




-----------------------------------------Estado
/*


CDESTADO
DSESTADO
*/
DROP TABLE IF EXISTS DimStatus;

SELECT DISTINCT 
    CDESTADO, 
    DSESTADO
INTO DimStatus
FROM Datasemilla;

ALTER TABLE DimStatus
ALTER COLUMN CDESTADO VARCHAR(50) NOT NULL;

ALTER TABLE DimStatus
ADD CONSTRAINT DimStatus_PK PRIMARY KEY (CDESTADO);

SELECT *
FROM DimStatus;


----------------------------------------EMPRESA
DROP TABLE IF EXISTS DimCompany;

SELECT DISTINCT
    CDCIA_USUARIA,
    DSCIA_USUARIA,
    NIT_COMPANIA,
    DSTIPO_ACTIVIDAD
INTO DimCompany
FROM DataSemilla

ALTER TABLE DimCompany
ALTER COLUMN CDCIA_USUARIA NVARCHAR(50) NOT NULL;

ALTER TABLE DimCompany
ADD CONSTRAINT DimCompanu_PK PRIMARY KEY (CDCIA_USUARIA);

SELECT *
FROM DimCompany;

---------------------------------------Transporte
/*
-- Transporte
MODO_TRANSPORTE
*/


DROP TABLE IF EXISTS DimTransport;

SELECT DISTINCT
MODO_TRANSPORTE
INTO DimTransport
FROM Datasemilla;

UPDATE DimTransport
SET MODO_TRANSPORTE = 'SIN ESPECIFICAR'
WHERE MODO_TRANSPORTE IS NULL; 

ALTER TABLE DimTransport
ALTER COLUMN MODO_TRANSPORTE NVARCHAR(50) NOT NULL;

ALTER TABLE DimTransport
ADD CONSTRAINT DimTransport_PK PRIMARY KEY (MODO_TRANSPORTE);

SELECT * FROM DimTransport;

-------------------------------------------- Importador
/*
NIT_IMPORTADOR
NOMBRE_IMPORTADOR
*/

DROP TABLE IF EXISTS DimImporter;

SELECT DISTINCT
NIT_IMPORTADOR,
NOMBRE_IMPORTADOR
INTO DimImporter
FROM Datasemilla
WHERE NIT_IMPORTADOR IS NOT NULL

ALTER TABLE DimImporter
ALTER COLUMN NIT_IMPORTADOR VARCHAR(50) NOT NULL;

ALTER TABLE DimImporter
ADD CONSTRAINT DimImporter_PK PRIMARY KEY (NIT_IMPORTADOR);

SELECT * FROM DimImporter;

