/*
-- Medidas

TASA_CAMBIO
CANTIDAD
PRECIO
PESO_BRUTO
PESO_NETO
FLETES
FOB

*/

/*
PK de dimensiones

NIT_IMPORTADOR, 
MODO_TRANSPORTE,
CDCIA_USUARIA,
CDESTADO,
CDTRANSACCION,
siaID,
ProductId,
DateId,
CountryId
*/

/*
COD_ZONAFRANCA
CDCIA_USUARIA
DSCIA_USUARIA
NIT_COMPANIA
DSTIPO_ACTIVIDAD
FMM
CDTRANSACCION
DSTRANSACCION
CDESTADO
DSESTADO
CDDOC_TRANSPORTE
CDDOC_EXPORTACION
CDFACTURA
TIPO
FECHA_DEFINITIVO
FECHA_APROBACION
FECHA_EJECUCION
FECHA_REVISION
FECHA_RECHAZO
FECHA_DIGITALIZACION
SNDECLARACION
NIT_IMPORTADOR
NOMBRE_IMPORTADOR
NIT_EXPORTADOR
NOMBRE_EXPORTADOR
NIT_SIA
NOMBRE_SIA
SUBPARTIDA
DESCRIP_SUBPARTIDA
EMBALAJE
COD_PAIS_ORIGEN
PAIS_ORIGEN
COD_PAIS_COMPRA
PAIS_COMPRA
COD_PAIS_DESTINO
PAIS_DESTINO
COD_PAIS_BANDERA
BANDERA
COD_PAIS_PROCEDENCIA
PAIS_PROCEDENCIA
UNIDAD_SUBPARTIDA
PESO_BRUTO
PESO_NETO
BULTOS
MODO_TRANSPORTE
TASA_CAMBIO
FOB
FLETES
COD_ITEM
ITEM
TIPO_ITEM
UNIDAD_COMERCIAL
UNIDAD_MEDIDA
CANTIDAD
PRECIO
NMCONVERSION
*/

DROP TABLE IF EXISTS FactImportRegistry;

CREATE TABLE FactImportRegistry(
    NIT_IMPORTADOR VARCHAR(50) ,
    MODO_TRANSPORTE NVARCHAR(50),
    CDCIA_USUARIA NVARCHAR(50),
    CDESTADO VARCHAR(50),
    CDTRANSACCION INT,
    siaID INT,
    ProductId INT,
    DateId INT,
    CountryId INT,
    TASA_CAMBIO float,
    CANTIDAD float,
    PRECIO float,
    PESO_BRUTO float,
    PESO_NETO float,
    FLETES float,
    FOB float,

    FOREIGN KEY (MODO_TRANSPORTE) REFERENCES DimTransport(MODO_TRANSPORTE),
    FOREIGN KEY (CDCIA_USUARIA) REFERENCES DimCompany(CDCIA_USUARIA),
    FOREIGN KEY (CDESTADO) REFERENCES DimStatus(CDESTADO),
    FOREIGN KEY (CDTRANSACCION) REFERENCES DimTransaction(CDTRANSACCION),
    FOREIGN KEY (siaID) REFERENCES DimSia(siaID),
    FOREIGN KEY (ProductId) REFERENCES DimProduct(ProductId),
    FOREIGN KEY (DateId) REFERENCES DimDate(DateId),
    FOREIGN KEY (CountryId) REFERENCES DimCountry(CountryId),
    FOREIGN KEY (NIT_IMPORTADOR) REFERENCES DimImporter(NIT_IMPORTADOR)
);


SELECT * FROM FactImportRegistry;

