/*
-- Medidas

TASA_CAMBIO
CANTIDAD
PRECIO
PESO_BRUTO
PESO_NETO
FLETES
FOB

*/

/*
PK de dimensiones

NIT_IMPORTADOR, 
MODO_TRANSPORTE,
CDCIA_USUARIA,
CDESTADO,
CDTRANSACCION,
siaID,
ProductId,
DateId,
CountryId
*/

/*
COD_ZONAFRANCA
CDCIA_USUARIA
DSCIA_USUARIA
NIT_COMPANIA
DSTIPO_ACTIVIDAD
FMM
CDTRANSACCION
DSTRANSACCION
CDESTADO
DSESTADO
CDDOC_TRANSPORTE
CDDOC_EXPORTACION
CDFACTURA
TIPO
FECHA_DEFINITIVO
FECHA_APROBACION
FECHA_EJECUCION
FECHA_REVISION
FECHA_RECHAZO
FECHA_DIGITALIZACION
SNDECLARACION
NIT_IMPORTADOR
NOMBRE_IMPORTADOR
NIT_EXPORTADOR
NOMBRE_EXPORTADOR
NIT_SIA
NOMBRE_SIA
SUBPARTIDA
DESCRIP_SUBPARTIDA
EMBALAJE
COD_PAIS_ORIGEN
PAIS_ORIGEN
COD_PAIS_COMPRA
PAIS_COMPRA
COD_PAIS_DESTINO
PAIS_DESTINO
COD_PAIS_BANDERA
BANDERA
COD_PAIS_PROCEDENCIA
PAIS_PROCEDENCIA
UNIDAD_SUBPARTIDA
PESO_BRUTO
PESO_NETO
BULTOS
MODO_TRANSPORTE
TASA_CAMBIO
FOB
FLETES
COD_ITEM
ITEM
TIPO_ITEM
UNIDAD_COMERCIAL
UNIDAD_MEDIDA
CANTIDAD
PRECIO
NMCONVERSION
*/
SELECT *
FROM FactImportRegistry;

WITH FechaRechazoNoNull AS (
SELECT dd.DateDay, dd.DateHour, dd.DateId, dd.DateMonth, dd.DateYear
FROM DimDate dd
INNER JOIN DataSemilla ds ON
    (DATEPART(WEEKDAY,ds.FECHA_RECHAZO) = dd.DateDay) AND
    (DATEPART(MONTH,ds.FECHA_RECHAZO) = dd.DateMonth) AND
    (DATEPART(YEAR,ds.FECHA_RECHAZO) = dd.DateYear) AND
    (DATEPART(HOUR,ds.FECHA_RECHAZO) = dd.DateHour)

), FechaRechazoNull AS(
SELECT dd.DateDay, dd.DateHour, dd.DateId, dd.DateMonth, dd.DateYear
FROM DimDate dd
INNER JOIN DataSemilla ds ON

     (DATEPART(WEEKDAY,ds.FECHA_RECHAZO) IS NULL AND dd.DateDay IS NULL)
), FechaRechazo AS(

SELECT * FROM FechaRechazoNoNull UNION ALL (
    SELECT * FROM FechaRechazoNull
)
) SELECT * FROM FechaRechazo;


-- SELECT dd.DateId
-- FROM DataSemilla ds
--     INNER JOIN DimDate dd ON
--     (DATEPART(WEEKDAY,ds.FECHA_RECHAZO) = dd.DateDay) AND
--         (DATEPART(MONTH,ds.FECHA_RECHAZO) = dd.DateMonth) AND
--         (DATEPART(YEAR,ds.FECHA_RECHAZO) = dd.DateYear) AND
--         (DATEPART(HOUR,ds.FECHA_RECHAZO) = dd.DateHour)
--         OR
--         (DATEPART(WEEKDAY,ds.FECHA_RECHAZO) IS NULL AND dd.DateDay IS NULL)