/*
-- Omitidos

EMBALAJE
SNDECLARACION
NIT_EXPORTADOR
NOMBRE_EXPORTADOR
SUBPARTIDA
DESCRIP_SUBPARTIDA
UNIDAD_SUBPARTIDA
BULTOS
UNIDAD_COMERCIAL
NMCONVERSION
[B] COD_ZONAFRANCA
[B] COD_PAIS_PROCEDENCIA
[B] PAIS_PROCEDENCIA
[B] FMM
[B] CDFACTURA 
[B] CDDOC_TRANSPORTE
[B] CDDOC_EXPORTACION

-- Medidas

TASA_CAMBIO
CANTIDAD
PRECIO
PESO_BRUTO
PESO_NETO
FLETES
FOB

*/

DROP TABLE IF EXISTS FactImportRegistry;

DROP TABLE IF EXISTS DimCountry;
DROP TABLE IF EXISTS DimDate;
DROP TABLE IF EXISTS DimProduct;
DROP TABLE IF EXISTS DimSia;
DROP TABLE IF EXISTS DimTransactionType;
DROP TABLE IF EXISTS DimStatus;
DROP TABLE IF EXISTS DimCompany;
DROP TABLE IF EXISTS DimImporter;

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-------Paises
/*
-- Paises
Pais Cod_pais

COD_PAIS_ORIGEN
PAIS_ORIGEN
COD_PAIS_COMPRA
PAIS_COMPRA
COD_PAIS_DESTINO
PAIS_DESTINO
COD_PAIS_BANDERA
BANDERA
*/

CREATE TABLE [dbo].[DimCountry]
(
    [CountryId] [int] NOT NULL,
    [CountryName] [nvarchar](50) NULL,
    CONSTRAINT [DimCountry_PK] PRIMARY KEY CLUSTERED 
(
	[CountryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO DimCountry
    (CountryId, CountryName)
SELECT
    ISNULL(COD_PAIS_ORIGEN, 0) AS CountryId,
    PAIS_ORIGEN AS CountryName
FROM DataSemilla
GROUP BY COD_PAIS_ORIGEN, PAIS_ORIGEN;

UPDATE DimCountry
SET CountryId = 0, 
    CountryName = 'N/A'
WHERE CountryId IS NULL AND CountryName IS NULL


GO


--------TIEMPO

/*

-- Tiempo
Año Mes Dia Hora Cuarto Semestre 
FECHA_DEFINITIVO
FECHA_APROBACION
FECHA_EJECUCION
FECHA_REVISION
FECHA_RECHAZO
FECHA_DIGITALIZACION

*/

CREATE TABLE [dbo].[DimDate]
(
    [DateYear] [int] NULL,
    [DateMonth] [int] NULL,
    [DateDay] [int] NULL,
    [DateHour] [int] NULL,
    [DateWeekDay] [int] NULL,
    [DateWeekDayName] [nvarchar](30) NULL,
    [DateMonthName] [nvarchar](30) NULL,
    [DateId] [int] IDENTITY(1,1) NOT NULL,
    [Semester] [varchar](12) NULL,
    PRIMARY KEY CLUSTERED 
(
	[DateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

DECLARE @StartDate DATETIME;
DECLARE @EndDate DATETIME;
SET @StartDate = '2008-01-01';
SET @EndDate = '2028-12-31';

WITH
    DateSequence
    AS
    (
                    SELECT @StartDate AS DateTimeValue
        UNION ALL
            SELECT DATEADD(hour, 1, DateTimeValue)
            FROM DateSequence
            WHERE DateTimeValue < @EndDate
    )
INSERT INTO DimDate
    (DateYear, DateMonth, DateDay, DateHour, DateWeekDay, DateWeekDayName, DateMonthName)
SELECT
    YEAR(DateTimeValue) AS DateYear,
    MONTH(DateTimeValue) AS DateMonth,
    DAY(DateTimeValue) AS DateDay,
    DATEPART(hour,DateTimeValue) AS DateHour,
    DATEPART(WEEKDAY, DateTimeValue) AS DateWeekDay,
    DATENAME(WEEKDAY, DateTimeValue) AS DateWeekDayName,
    DATENAME(MONTH, DateTimeValue) AS DateMonthName
FROM DateSequence
OPTION
(MAXRECURSION
0);

INSERT INTO DimDate
    (
    DateDay,
    DateHour,
    DateMonth,
    DateYear,
    DateWeekDay,
    DateMonthName,
    DateWeekDayName
    )
VALUES
    (NULL, NULL, NULL, NULL, NULL, 'Sin Mes', 'Sin Día de Semana');


UPDATE DimDate
SET Semester = CASE WHEN DateMonth <= 6 THEN '1st semestre'
                WHEN DateMonth IS NULL THEN 'Sin semestre'
                    ELSE '2nd semestre'
               END;
        

GO

---------------------------------------PRODUCTO
/*
COD_ITEM
ITEM
TIPO_ITEM
UNIDAD_MEDIDA
EMBALAJE
*/
CREATE TABLE [dbo].[DimProduct](
	[COD_ITEM] [nvarchar](50) NULL,
	[ITEM] [nvarchar](100) NULL,
	[TIPO_ITEM] [nvarchar](50) NULL,
	[UNIDAD_MEDIDA] [nvarchar](50) NULL,
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO DimProduct (COD_ITEM, ITEM, TIPO_ITEM, UNIDAD_MEDIDA)
SELECT DISTINCT
    COD_ITEM,
    ITEM,
    TIPO_ITEM,
    UNIDAD_MEDIDA
FROM Datasemilla;


GO


---------------------------------------SIA

/*

NIT_SIA
NOMBRE_SIA

*/
CREATE TABLE [dbo].[DimSia](
	[NIT_SIA] [nvarchar](50) NULL,
	[NOMBRE_SIA] [nvarchar](50) NULL,
	[siaID] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[siaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO DimSia(NIT_SIA, NOMBRE_SIA)
SELECT DISTINCT
    NIT_SIA,
    NOMBRE_SIA
FROM Datasemilla;


GO

--------------------------------------- TRANSACTION


/*
TIPO
CDTRANSACCION
DSTRANSACCION
*/
CREATE TABLE [dbo].[DimTransactionType](
	[CDTRANSACCION] [int] NOT NULL,
	[DSTRANSACCION] [nvarchar](100) NULL,
 CONSTRAINT [DimTransaction_PK] PRIMARY KEY CLUSTERED 
(
	[CDTRANSACCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO DimTransactionType(CDTRANSACCION, DSTRANSACCION)
SELECT DISTINCT
    CDTRANSACCION,
    DSTRANSACCION
FROM Datasemilla;


GO


-----------------------------------------Estado
/*


CDESTADO
DSESTADO
*/
CREATE TABLE [dbo].[DimStatus](
	[CDESTADO] [varchar](50) NOT NULL,
	[DSESTADO] [nvarchar](50) NULL,
 CONSTRAINT [DimStatus_PK] PRIMARY KEY CLUSTERED 
(
	[CDESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO DimStatus(CDESTADO, DSESTADO)
SELECT DISTINCT
    CDESTADO,
    DSESTADO
FROM Datasemilla;

UPDATE DimStatus
SET CDESTADO = 0 
WHERE CDESTADO IS NULL;

GO


----------------------------------------EMPRESA

CREATE TABLE [dbo].[DimCompany](
	[CDCIA_USUARIA] [nvarchar](50) NOT NULL,
	[DSCIA_USUARIA] [nvarchar](50) NULL,
	[NIT_COMPANIA] [nvarchar](50) NULL,
	[DSTIPO_ACTIVIDAD] [nvarchar](50) NULL,
 CONSTRAINT [DimCompanu_PK] PRIMARY KEY CLUSTERED 
(
	[CDCIA_USUARIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO DimCompany(CDCIA_USUARIA, DSCIA_USUARIA, NIT_COMPANIA, DSTIPO_ACTIVIDAD)
SELECT DISTINCT
    CDCIA_USUARIA,
    DSCIA_USUARIA,
    NIT_COMPANIA,
    DSTIPO_ACTIVIDAD
FROM DataSemilla;


GO

-------------------------------------------- Importador
/*
NIT_IMPORTADOR
NOMBRE_IMPORTADOR
*/

CREATE TABLE [dbo].[DimImporter](
	[NIT_IMPORTADOR] [varchar](50) NOT NULL,
	[NOMBRE_IMPORTADOR] [nvarchar](100) NULL,
 CONSTRAINT [DimImporter_PK] PRIMARY KEY CLUSTERED 
(
	[NIT_IMPORTADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO DimImporter(NIT_IMPORTADOR, NOMBRE_IMPORTADOR)
SELECT DISTINCT
    NIT_IMPORTADOR,
    NOMBRE_IMPORTADOR
FROM Datasemilla
WHERE NIT_IMPORTADOR IS NOT NULL

GO
------------------------------------------------FACTS

CREATE TABLE FactImportRegistry
(
    IdFact INT IDENTITY(1,1) PRIMARY KEY,

    NIT_IMPORTADOR VARCHAR(50) ,
    MODO_TRANSPORTE NVARCHAR(50),
    CDCIA_USUARIA NVARCHAR(50),
    CDESTADO VARCHAR(50),
    CDTRANSACCION INT,
    siaID INT,
    ProductId INT,
    DateId INT,
    CountryId INT,


    CANTIDAD float,
    PRECIO float,
    PESO_BRUTO float,
    PESO_NETO float,
    -- TODO: Ver cual de los campos es calculados. 
    FLETES float,
    FOB float,

    FOREIGN KEY (CDCIA_USUARIA) REFERENCES DimCompany(CDCIA_USUARIA),
    FOREIGN KEY (CDESTADO) REFERENCES DimStatus(CDESTADO),
    FOREIGN KEY (CDTRANSACCION) REFERENCES DimTransactionType(CDTRANSACCION),
    FOREIGN KEY (siaID) REFERENCES DimSia(siaID),
    FOREIGN KEY (ProductId) REFERENCES DimProduct(ProductId),
    FOREIGN KEY (DateId) REFERENCES DimDate(DateId),
    FOREIGN KEY (CountryId) REFERENCES DimCountry(CountryId),
    FOREIGN KEY (NIT_IMPORTADOR) REFERENCES DimImporter(NIT_IMPORTADOR)
);

GO

